# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install \
          pytest \
          tox
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test Project
      run: |
        tox -e py

    - name: Lint
      continue-on-error: true
      run: |
        tox -e lint

    - name: Check - Codestyle
      if: ${{ matrix.python-version }}" == '3.8'
      run: |
        tox -e codestyle

    - name: Check - Lint
      if: ${{ matrix.python-version }}" == '3.8'
      run: |
        tox -e pypi-lint

    - name: Check - Security
      if: ${{ matrix.python-version }}" == '3.8'
      run: |
        tox -e security

    - name: Debug
      run: |
        printenv
        echo "Py version: ${{ matrix.python-version }}"
